# Generated by Django 5.2.4 on 2025-08-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='第几周')),
                ('day', models.CharField(max_length=3, verbose_name='星期几')),
                ('lesson', models.CharField(max_length=50, verbose_name='课程')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('day_time', models.IntegerField(verbose_name='上午/下午/晚上')),
                ('startime', models.DateField(verbose_name='学期开始时间')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('location', models.CharField(max_length=50, verbose_name='教室位置')),
                ('teacher', models.CharField(max_length=20, verbose_name='教师名字')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.logindata', verbose_name='用户')),
            ],
            options={
                'db_table': 'lessonTable',
            },
        ),
    ]
